import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { colors, radius, spacing } from "@/constants/design";
import { getAcademicTrack } from "@/lib/academic";

export default function AcademicModuleScreen() {
  const router = useRouter(); const { program, module } = useLocalSearchParams<{ program: string; module: string }>(); const track = getAcademicTrack(program); const moduleIndex = Math.max(0, Math.min(track.modules.length - 1, Number(module) || 0)); const currentModule = track.modules[moduleIndex];
  return <><Stack.Screen options={{ headerShown: false }} /><ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5" containerClassName="bg-[#F5F7F9]"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>←  Back to {track.label}</Text></Pressable><View style={[styles.hero, { backgroundColor: currentModule.color }]}><Text style={styles.kicker}>{track.label.toUpperCase()} · MODULE {String(moduleIndex + 1).padStart(2, "0")}</Text><Text style={styles.icon}>{currentModule.icon}</Text><Text style={styles.title}>{currentModule.title}</Text><Text style={styles.subtitle}>{currentModule.subtitle}</Text><Text style={styles.meta}>{currentModule.lessons.length} lessons · 10–15 min each</Text></View><View style={styles.startCard}><Text style={styles.startKicker}>READY TO BEGIN?</Text><Text style={styles.startTitle}>{currentModule.lessons[0]}</Text><Text style={styles.startText}>Start with a short, focused lesson. You will learn useful expressions, listen to examples and finish with a quick check.</Text><Pressable onPress={() => router.push(`/academic/${track.id}/module/${moduleIndex}/lesson/1` as never)} style={styles.startButton}><Text style={styles.startButtonText}>Start lesson  →</Text></Pressable></View><Text style={styles.sectionTitle}>Module lessons</Text>{currentModule.lessons.map((lesson, index) => <Pressable key={lesson} onPress={() => router.push(`/academic/${track.id}/module/${moduleIndex}/lesson/${index + 1}` as never)} style={styles.lessonRow}><View style={[styles.lessonNumber, index === 0 && styles.lessonNumberActive]}><Text style={[styles.lessonNumberText, index === 0 && styles.lessonNumberTextActive]}>{index + 1}</Text></View><View style={styles.lessonCopy}><Text style={styles.lessonTitle}>{lesson}</Text><Text style={styles.lessonDetail}>{index === 0 ? "Ready to start" : "Unlock after the previous lesson"}</Text></View><Text style={styles.arrow}>{index === 0 ? "→" : "•"}</Text></Pressable>)}<View style={styles.note}><Text style={styles.noteIcon}>✦</Text><Text style={styles.noteText}>Your progress is saved locally. Missed concepts will return in Smart Review.</Text></View></ScrollView></ScreenContainer></>;
}

const styles = StyleSheet.create({ content: { paddingTop: spacing.md, paddingBottom: 42 }, back: { alignSelf: "flex-start", paddingVertical: 8 }, backText: { color: colors.inkSoft, fontSize: 12, fontWeight: "800" }, hero: { borderRadius: radius.lg, padding: spacing.xl, marginTop: spacing.sm, marginBottom: spacing.md }, kicker: { color: colors.primary, fontSize: 9, fontWeight: "900", letterSpacing: 1.3 }, icon: { fontSize: 30, marginTop: 16 }, title: { color: colors.ink, fontSize: 31, fontWeight: "900", marginTop: 7 }, subtitle: { color: colors.inkSoft, fontSize: 13, marginTop: 5 }, meta: { color: colors.inkSoft, fontSize: 10, fontWeight: "800", marginTop: 20 }, startCard: { backgroundColor: colors.ink, borderRadius: radius.md, padding: spacing.lg, marginBottom: spacing.xl }, startKicker: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1.3 }, startTitle: { color: colors.white, fontSize: 20, fontWeight: "900", marginTop: 9 }, startText: { color: "#AAB5BD", fontSize: 11, lineHeight: 17, marginTop: 6 }, startButton: { backgroundColor: colors.gold, borderRadius: 12, paddingVertical: 12, alignItems: "center", marginTop: 16 }, startButtonText: { color: colors.ink, fontSize: 12, fontWeight: "900" }, sectionTitle: { color: colors.ink, fontSize: 20, fontWeight: "900", marginBottom: spacing.sm }, lessonRow: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, flexDirection: "row", alignItems: "center", marginBottom: spacing.sm }, lessonNumber: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.line, alignItems: "center", justifyContent: "center" }, lessonNumberActive: { backgroundColor: colors.primary }, lessonNumberText: { color: colors.muted, fontWeight: "900" }, lessonNumberTextActive: { color: colors.white }, lessonCopy: { flex: 1, marginLeft: spacing.md }, lessonTitle: { color: colors.ink, fontSize: 13, fontWeight: "900" }, lessonDetail: { color: colors.muted, fontSize: 10, marginTop: 3 }, arrow: { color: colors.primary, fontSize: 18, fontWeight: "900" }, note: { backgroundColor: colors.lilac, borderRadius: radius.md, padding: spacing.md, flexDirection: "row", gap: 9, marginTop: spacing.md }, noteIcon: { color: colors.lilacStrong, fontSize: 17 }, noteText: { flex: 1, color: colors.inkSoft, fontSize: 10, lineHeight: 15 },
});
