import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { colors, radius, spacing } from "@/constants/design";
import { getAcademicTrack } from "@/lib/academic";
import { speakNatural } from "@/lib/speech";

export default function AcademicLessonScreen() {
  const router = useRouter(); const { program, module, lesson } = useLocalSearchParams<{ program: string; module: string; lesson: string }>(); const track = getAcademicTrack(program); const moduleIndex = Number(module) || 0; const lessonIndex = Math.max(0, (Number(lesson) || 1) - 1); const currentModule = track.modules[moduleIndex] ?? track.modules[0]; const lessonTitle = currentModule.lessons[lessonIndex] ?? currentModule.lessons[0]; const examples = track.id === "bepc" ? [{ word: "understand", meaning: "comprendre", example: "I understand the question." }, { word: "answer", meaning: "réponse", example: "Write your answer clearly." }, { word: "practice", meaning: "s'entraîner", example: "Practice every day." }] : track.id === "bac" ? [{ word: "argument", meaning: "argument", example: "Give one strong argument." }, { word: "however", meaning: "cependant", example: "However, the result is different." }, { word: "evidence", meaning: "preuve", example: "Use evidence in your essay." }] : [{ word: "research", meaning: "recherche", example: "The research supports this view." }, { word: "evidence", meaning: "preuve", example: "We need evidence for the claim." }, { word: "therefore", meaning: "donc", example: "Therefore, the conclusion is clear." }];
  return <><Stack.Screen options={{ headerShown: false }} /><ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5" containerClassName="bg-[#F5F7F9]"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>←  Back to module</Text></Pressable><View style={styles.header}><Text style={styles.kicker}>{track.label.toUpperCase()} · LESSON {lessonIndex + 1}</Text><Text style={styles.title}>{lessonTitle}</Text><Text style={styles.subtitle}>Listen, learn and use the language in context.</Text></View><Text style={styles.sectionTitle}>Key language</Text>{examples.map((item) => <View key={item.word} style={styles.wordCard}><Pressable onPress={() => { void speakNatural(item.word); }} style={styles.speaker}><Text style={styles.speakerText}>▶</Text></Pressable><View style={styles.wordCopy}><Text style={styles.word}>{item.word}</Text><Text style={styles.meaning}>{item.meaning}</Text><Text style={styles.example}>{item.example}</Text></View></View>)}<View style={styles.practice}><Text style={styles.practiceKicker}>QUICK CHECK</Text><Text style={styles.practiceTitle}>Which word means “{examples[0].meaning}”?</Text><Pressable onPress={() => router.push(`/academic/${track.id}/test` as never)} style={styles.practiceButton}><Text style={styles.practiceButtonText}>Continue to practice  →</Text></Pressable></View><Pressable onPress={() => router.push(`/academic/${track.id}/module/${moduleIndex}` as never)} style={styles.finish}><Text style={styles.finishText}>Finish lesson</Text></Pressable></ScrollView></ScreenContainer></>;
}

const styles = StyleSheet.create({ content: { paddingTop: spacing.md, paddingBottom: 42 }, back: { alignSelf: "flex-start", paddingVertical: 8 }, backText: { color: colors.inkSoft, fontSize: 12, fontWeight: "800" }, header: { backgroundColor: colors.ink, borderRadius: radius.lg, padding: spacing.xl, marginTop: spacing.sm, marginBottom: spacing.xl }, kicker: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1.3 }, title: { color: colors.white, fontSize: 30, fontWeight: "900", marginTop: 10 }, subtitle: { color: "#AAB5BD", fontSize: 12, lineHeight: 18, marginTop: 6 }, sectionTitle: { color: colors.ink, fontSize: 20, fontWeight: "900", marginBottom: spacing.sm }, wordCard: { backgroundColor: colors.white, borderRadius: radius.md, padding: spacing.md, flexDirection: "row", alignItems: "center", marginBottom: spacing.sm }, speaker: { width: 40, height: 40, borderRadius: 13, backgroundColor: colors.goldSoft, alignItems: "center", justifyContent: "center" }, speakerText: { color: colors.primary, fontSize: 12 }, wordCopy: { marginLeft: spacing.md }, word: { color: colors.ink, fontSize: 16, fontWeight: "900" }, meaning: { color: colors.primary, fontSize: 11, marginTop: 2 }, example: { color: colors.muted, fontSize: 10, fontStyle: "italic", marginTop: 5 }, practice: { backgroundColor: colors.lilac, borderRadius: radius.md, padding: spacing.lg, marginTop: spacing.lg }, practiceKicker: { color: colors.lilacStrong, fontSize: 9, fontWeight: "900", letterSpacing: 1.2 }, practiceTitle: { color: colors.ink, fontSize: 17, lineHeight: 23, fontWeight: "900", marginTop: 8 }, practiceButton: { backgroundColor: colors.primary, borderRadius: 12, paddingVertical: 12, alignItems: "center", marginTop: 15 }, practiceButtonText: { color: colors.white, fontSize: 11, fontWeight: "900" }, finish: { alignItems: "center", padding: 16 }, finishText: { color: colors.primary, fontSize: 12, fontWeight: "900" },
});
