export type AcademicProgram = "bepc" | "bac" | "university";
export type AcademicQuestion = { prompt: string; answer: string; choices: string[]; explanation: string };
export type AcademicModule = { title: string; subtitle: string; icon: string; color: string; lessons: string[] };
export type AcademicTrack = { id: AcademicProgram; label: string; shortLabel: string; description: string; level: string; accent: string; modules: AcademicModule[]; questions: AcademicQuestion[] };

export const academicTracks: AcademicTrack[] = [
  { id: "bepc", label: "BEPC", shortLabel: "Collège", description: "Bases solides pour comprendre, écrire et parler en anglais au collège.", level: "A1–A2", accent: "#DDEBFF", modules: [{ title: "Everyday English", subtitle: "Se présenter et parler de soi", icon: "☀", color: "#DDEBFF", lessons: ["Greetings", "Family & friends", "Daily routines"] }, { title: "School life", subtitle: "La classe, les consignes et les loisirs", icon: "▣", color: "#E4F6E8", lessons: ["My classroom", "School subjects", "Free time"] }, { title: "Exam essentials", subtitle: "Compréhension et rédaction courte", icon: "✓", color: "#FFE9D2", lessons: ["Reading clues", "Writing a message", "Revision quiz"] }], questions: [{ prompt: "Choose the correct sentence.", answer: "I am a student.", choices: ["I am a student.", "I student am.", "I is student.", "Student I ams."], explanation: "Use am with I: I am a student." }, { prompt: "What does ‘library’ mean?", answer: "Bibliothèque", choices: ["Bibliothèque", "Laboratoire", "Terrain", "Cantine"], explanation: "Library means bibliothèque." }, { prompt: "Complete: She ___ from Douala.", answer: "is", choices: ["is", "are", "am", "be"], explanation: "Use is with she." }, { prompt: "Choose the polite request.", answer: "Can I borrow your pen, please?", choices: ["Can I borrow your pen, please?", "Give pen.", "You pen me.", "Pen now!"], explanation: "Can I… please? is a polite request." }, { prompt: "What is the past of go?", answer: "went", choices: ["went", "goed", "goes", "going"], explanation: "The irregular past of go is went." }] },
  { id: "bac", label: "Baccalauréat", shortLabel: "Lycée", description: "Prépare les compétences du lycée : argumentation, grammaire et compréhension.", level: "B1–B2", accent: "#FFE9D2", modules: [{ title: "Grammar toolkit", subtitle: "Temps, modaux et conditionnels", icon: "Aa", color: "#FFE9D2", lessons: ["Tenses review", "Modals", "Conditionals"] }, { title: "Reading & ideas", subtitle: "Analyser un texte et défendre une idée", icon: "◌", color: "#F1E4FF", lessons: ["Main ideas", "Connectors", "Giving an opinion"] }, { title: "Exam production", subtitle: "Rédiger avec précision et nuance", icon: "↗", color: "#E4F6E8", lessons: ["Essay structure", "Formal email", "Oral presentation"] }], questions: [{ prompt: "If I had more time, I ___ another language.", answer: "would learn", choices: ["would learn", "will learned", "learn", "am learn"], explanation: "The second conditional uses would + base verb." }, { prompt: "Choose the best connector: The task was difficult; ___, we finished it.", answer: "however", choices: ["however", "because", "although", "unless"], explanation: "However contrasts two complete ideas." }, { prompt: "‘Reliable’ is closest in meaning to…", answer: "trustworthy", choices: ["trustworthy", "expensive", "temporary", "difficult"], explanation: "Reliable means trustworthy." }, { prompt: "Choose the formal opening.", answer: "Dear Sir or Madam,", choices: ["Dear Sir or Madam,", "Hey you,", "Hi buddy!", "Listen,"], explanation: "Dear Sir or Madam is a formal opening." }, { prompt: "Which sentence expresses an opinion?", answer: "In my view, education should be accessible.", choices: ["In my view, education should be accessible.", "The exam starts at eight.", "She lives in Yaoundé.", "The book has ten pages."], explanation: "In my view signals an opinion." }] },
  { id: "university", label: "Université", shortLabel: "Académique", description: "Anglais académique et professionnel pour réussir les études et les présentations.", level: "B2–C1", accent: "#E4F6E8", modules: [{ title: "Academic English", subtitle: "Lire, citer et synthétiser", icon: "◫", color: "#E4F6E8", lessons: ["Academic vocabulary", "Summaries", "Sources & citations"] }, { title: "Critical thinking", subtitle: "Construire une analyse claire", icon: "◇", color: "#DDEBFF", lessons: ["Claims & evidence", "Cause and effect", "Comparing viewpoints"] }, { title: "Campus & career", subtitle: "Présenter son projet avec assurance", icon: "↗", color: "#F1E4FF", lessons: ["Presentation skills", "Interview English", "Professional email"] }], questions: [{ prompt: "Choose the strongest academic claim.", answer: "The evidence suggests that practice improves retention.", choices: ["The evidence suggests that practice improves retention.", "Practice is nice, I think.", "Everyone knows practice.", "Retention maybe practice."], explanation: "Academic claims should be precise and supported." }, { prompt: "Which phrase introduces evidence?", answer: "According to the study,", choices: ["According to the study,", "I feel like,", "Hey,", "No way,"], explanation: "According to the study introduces a source." }, { prompt: "Complete: The results ___ a significant improvement.", answer: "indicate", choices: ["indicate", "indicates", "indicating", "is indicate"], explanation: "Results is plural, so use indicate." }, { prompt: "Choose the best presentation transition.", answer: "Let us now turn to the second point.", choices: ["Let us now turn to the second point.", "Next thing, okay?", "And stuff.", "Point two, listen."], explanation: "This is a clear formal transition." }, { prompt: "What does ‘therefore’ express?", answer: "a consequence", choices: ["a consequence", "a contrast", "a question", "a greeting"], explanation: "Therefore introduces a consequence." }] },
];

export function getAcademicTrack(id: string) { return academicTracks.find((track) => track.id === id) ?? academicTracks[0]; }
