import type { Level, Word } from "./content";

export type PracticeMode = "Daily" | "Vocabulary" | "Listening" | "Pronunciation" | "Mistakes";
export function calculateScore(correct: number, total: number) { if (total <= 0) return 0; return Math.round(Math.max(0, Math.min(1, correct / total)) * 100); }
export function chooseDistractors(word: Word, words: Word[], count = 3) { return words.filter((candidate) => candidate.id !== word.id).slice(0, count).map((candidate) => candidate.french); }
export function weakWordIds(mistakes: string[], learnedWords: string[], limit = 5) { return Array.from(new Set(mistakes.length > 0 ? mistakes : learnedWords)).slice(0, limit); }
export function pronunciationFeedback(score: number, word: Word) { if (score >= 85) return { title: "Good pronunciation", detail: "Clear and confident. Keep your rhythm natural." }; if (score >= 70) return { title: "Almost there", detail: `Focus on the stressed sound in ${word.english}.` }; return { title: "Try again", detail: `Slow down and repeat ${word.phonetic} carefully.` }; }
export function pronunciationScore(target: string, transcript: string) { const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9' ]/g, "").split(/\s+/).filter(Boolean); const expected = normalize(target); const spoken = normalize(transcript); if (!expected.length || !spoken.length) return 0; const table = Array.from({ length: expected.length + 1 }, () => Array<number>(spoken.length + 1).fill(0)); for (let row = 1; row <= expected.length; row += 1) for (let column = 1; column <= spoken.length; column += 1) table[row][column] = expected[row - 1] === spoken[column - 1] ? table[row - 1][column - 1] + 1 : Math.max(table[row - 1][column], table[row][column - 1]); return calculateScore(table[expected.length][spoken.length], expected.length); }
export function shouldAutoStopVoice(input: { metering: number; hasDetectedSpeech: boolean; silenceDurationMillis: number; durationMillis: number }) { const speechThreshold = -45; const silenceWindow = 900; const maximumDuration = 8000; if (input.durationMillis >= maximumDuration) return true; return input.hasDetectedSpeech && input.metering <= speechThreshold && input.silenceDurationMillis >= silenceWindow; }
export function lessonXp(level: Level, streak: number, score = 100) { const base = level === "Advanced" ? 40 : level === "Intermediate" ? 32 : 25; const streakBonus = Math.min(15, Math.max(0, streak - 1) * 2); const scoreBonus = score >= 90 ? 8 : score >= 75 ? 4 : 0; return base + streakBonus + scoreBonus; }
export function dueReviewWordIds(reviewDueAt: Record<string, string>, today = new Date().toISOString().slice(0, 10), limit = 5) { return Object.entries(reviewDueAt).filter(([, dueAt]) => dueAt <= today).sort((a, b) => a[1].localeCompare(b[1])).slice(0, limit).map(([wordId]) => wordId); }
