import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { getAcademicTrack } from "@/lib/academic";
import { useAppState } from "@/lib/app-state";
import { calculateScore, lessonXp } from "@/lib/practice";

export default function AcademicTestScreen() {
  const router = useRouter(); const { program } = useLocalSearchParams<{ program: string }>(); const track = getAcademicTrack(program); const { recordTest, streak } = useAppState();
  const questions = useMemo(() => track.questions, [track]); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [answers, setAnswers] = useState<boolean[]>([]); const [finished, setFinished] = useState(false); const question = questions[index]; const score = calculateScore(answers.filter(Boolean).length, questions.length);
  const choose = (choice: string) => { if (selected || finished) return; setSelected(choice); setAnswers((current) => [...current, choice === question.answer]); };
  const next = () => { if (index === questions.length - 1) { const finalScore = calculateScore([...answers].filter(Boolean).length, questions.length); recordTest(finalScore); setFinished(true); return; } setIndex((value) => value + 1); setSelected(null); };
  const restart = () => { setIndex(0); setSelected(null); setAnswers([]); setFinished(false); };
  return <><Stack.Screen options={{ headerShown: false }} /><ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5" containerClassName="bg-[#F7F8FA]"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>{!finished ? <><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>←</Text></Pressable><Text style={styles.kicker}>{track.label.toUpperCase()} TEST</Text><Text style={styles.counter}>{index + 1}/{questions.length}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${((index + 1) / questions.length) * 100}%` }]} /></View><Text style={styles.trackLabel}>{track.level} · Diagnostic test</Text><Text style={styles.title}>{question.prompt}</Text><View style={styles.answers}>{question.choices.map((choice) => <Pressable key={choice} onPress={() => choose(choice)} style={[styles.answer, selected === choice && (choice === question.answer ? styles.correct : styles.wrong)]}><Text style={styles.answerText}>{choice}</Text><Text style={styles.mark}>{selected === choice ? (choice === question.answer ? "✓" : "×") : ""}</Text></Pressable>)}</View>{selected && <View style={styles.explanation}><Text style={styles.explanationTitle}>{selected === question.answer ? "Correct" : "Review this"}</Text><Text style={styles.explanationText}>{question.explanation}</Text></View>}<Pressable disabled={!selected} onPress={next} style={[styles.next, !selected && styles.disabled]}><Text style={styles.nextText}>{index === questions.length - 1 ? "See my result" : "Next question  →"}</Text></Pressable></> : <><Text style={styles.kicker}>{track.label.toUpperCase()} · RESULT</Text><Text style={styles.title}>Your academic path starts here.</Text><View style={styles.result}><Text style={styles.score}>{score}%</Text><Text style={styles.resultCaption}>{answers.filter(Boolean).length}/{questions.length} correct answers</Text><Text style={styles.resultMessage}>{score >= 80 ? `Strong start. You earned ${lessonXp(score >= 90 ? "Advanced" : "Intermediate", streak, score)} XP.` : "Your missed concepts are ready for review in Practice."}</Text></View><View style={styles.actions}><Pressable onPress={restart} style={styles.secondary}><Text style={styles.secondaryText}>Try again</Text></Pressable><Pressable onPress={() => router.replace(`/academic/${track.id}` as never)} style={styles.primary}><Text style={styles.primaryText}>View pathway</Text></Pressable></View></>}</ScrollView></ScreenContainer></>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 42 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }, back: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, backText: { color: "#101821", fontSize: 23 }, kicker: { color: "#A1483C", fontSize: 10, fontWeight: "900", letterSpacing: 1.4 }, counter: { color: "#7C8791", fontSize: 12 }, track: { height: 8, borderRadius: 4, backgroundColor: "#E3E7EA", overflow: "hidden", marginBottom: 11 }, fill: { height: "100%", backgroundColor: "#A1483C" }, trackLabel: { color: "#7C8791", fontSize: 10, fontWeight: "800" }, title: { color: "#101821", fontSize: 28, lineHeight: 34, fontWeight: "900", marginTop: 10, marginBottom: 22 }, answers: { gap: 9 }, answer: { backgroundColor: "#FFFFFF", borderRadius: 15, padding: 15, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, answerText: { color: "#101821", fontSize: 13, lineHeight: 18, flex: 1 }, mark: { color: "#101821", fontWeight: "900", fontSize: 17 }, correct: { backgroundColor: "#DDF3E3" }, wrong: { backgroundColor: "#F9DCD7" }, explanation: { backgroundColor: "#F1E4FF", borderRadius: 16, padding: 15, marginTop: 17 }, explanationTitle: { color: "#A1483C", fontSize: 12, fontWeight: "900" }, explanationText: { color: "#57616B", fontSize: 11, lineHeight: 17, marginTop: 5 }, next: { backgroundColor: "#A1483C", height: 52, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 22 }, nextText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, disabled: { opacity: 0.35 }, result: { backgroundColor: "#101821", borderRadius: 23, padding: 24, alignItems: "center", marginTop: 14 }, score: { color: "#F0A04B", fontSize: 58, fontWeight: "900" }, resultCaption: { color: "#B8C0C9", fontSize: 12, marginTop: -2 }, resultMessage: { color: "#FFFDF7", textAlign: "center", fontSize: 13, lineHeight: 20, marginTop: 20 }, actions: { flexDirection: "row", gap: 9, marginTop: 18 }, secondary: { flex: 1, backgroundColor: "#FFFFFF", borderRadius: 14, height: 48, alignItems: "center", justifyContent: "center" }, secondaryText: { color: "#A1483C", fontSize: 11, fontWeight: "900" }, primary: { flex: 1, backgroundColor: "#A1483C", borderRadius: 14, height: 48, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
});
